package com.smartfactory.exception;

public enum ErrorCode {
    // Auth & Users
    INVALID_CREDENTIALS,
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    UNAUTHORIZED,
    FORBIDDEN,
    INVALID_TOKEN,
    TOKEN_EXPIRED,
    USER_INACTIVE,
    EMAIL_NOT_VERIFIED,
    OTP_INVALID,
    OTP_EXPIRED,
    OTP_ALREADY_USED,
    OTP_MAX_ATTEMPTS,
    OTP_RESEND_TOO_SOON,
    RESET_TOKEN_INVALID,
    RESET_TOKEN_EXPIRED,

    // Machines
    MACHINE_NOT_FOUND,
    MACHINE_ALREADY_EXISTS,
    INVALID_MACHINE_STATUS,

    // Zones
    ZONE_NOT_FOUND,
    ZONE_ALREADY_EXISTS,

    // Groups
    GROUP_NOT_FOUND,
    GROUP_ALREADY_EXISTS,
    INVALID_OPERATOR_ROLE,
    INVALID_SUPERVISOR_ROLE,
    OPERATOR_ALREADY_IN_GROUP,
    OPERATOR_NOT_IN_GROUP,

    // Validation & Generic
    VALIDATION_ERROR,
    BAD_REQUEST,
    INTERNAL_SERVER_ERROR
}
